spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
#    url: "jdbc:mysql://eu-cdbr-west-02.cleardb.net/heroku_fe8d66a23f4c428?reconnect=true"
#    username: ${CLEARDB_USER}
#    password: ${CLEARDB_PWD}
    url: "jdbc:mysql://localhost:3306/photo_store?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: local
    password:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  sql:
#    init:
#      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    mvc:
      hiddenmethod:
        filter:
          enabled: true

#Cloudinary Properties
cloudinary:
  api-key: 124759773655678
  api-secret: ${CLOUDINARY_API_SECRET}
  cloud-name: vtotev